version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
