name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

env:
  VERSION: "1.5.9"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag
        shell: bash
        run: echo "tag=`echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | awk '{ if ($0 == "main") {print "latest"} else {print $0;} }'`" >> $GITHUB_OUTPUT
        id: extract_tag
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ProductiveOps Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERREGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERREGISTRY_PASSWORD }}
      - name: Build and Push Server
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          file: Dockerfile.server
          push: true
          platforms: linux/amd64,linux/arm64
          tags: javastraat/dokemon-server:${{ steps.extract_tag.outputs.tag }}${{ steps.extract_tag.outputs.tag == 'latest' && format(' , javastraat/dokemon-server:{0}', env.VERSION) || '' }}
      - name: Build and Push Agent
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          file: Dockerfile.agent
          push: true
          platforms: linux/amd64,linux/arm64
          tags: javastraat/dokemon-agent:${{ steps.extract_tag.outputs.tag }}${{ steps.extract_tag.outputs.tag == 'latest' && format(' , javastraat/dokemon-agent:{0}', env.VERSION) || '' }}
